[feature] added find method
breskul/bibernate pull request #10
Opened 2023-03-29 15:24 UTC by artemyankovets

added find method

2023-03-29 19:33 UTC, Mikhail-Mikhailenko commented on src/main/java/com/breskul/bibernate/persistence/JdbcDao.java
> +    private static final String CHECK_YOUR_SQL_QUERY = "check your sql query";
How do you think about replace this error inside exception class?

2023-03-29 19:33 UTC, Mikhail-Mikhailenko commented on src/main/java/com/breskul/bibernate/persistence/JdbcDao.java
> +    private <T, E extends SQLException> T performReturningStatement(
I think we should avoid this construction. In the next PR we will have only one connection for this class

2023-03-30 17:19 UTC, artemyankovets commented on src/main/java/com/breskul/bibernate/persistence/JdbcDao.java
> +    private static final String CHECK_YOUR_SQL_QUERY = "check your sql query";
done

2023-03-31 12:25 UTC, Mikhail-Mikhailenko approved these changes

2023-03-31 13:15 UTC, artemyankovets commented on src/test/java/com/breskul/bibernate/persistence/EntityManagerImplTest.java
> +    }
Add one more test for Note when Person is null

2023-03-31 14:31 UTC, yuriyfomin17 requested changes
@artemyankovets third test does not pass 
<img width="1348" alt="Снимок экрана 2023-03-31 в 15 30 35" src="https://user-images.githubusercontent.com/44197746/229149372-21ade606-f257-4178-88d4-936aa354ee60.png">

2023-03-31 16:11 UTC, artemyankovets commented
> @artemyankovets third test does not pass <img alt="Снимок экрана 2023-03-31 в 15 30 35" width="1348" src="https://user-images.githubusercontent.com/44197746/229149372-21ade606-f257-4178-88d4-936aa354ee60.png">

pls pull the updated version

2023-03-31 16:13 UTC, yuriyfomin17 approved these changes

2023-03-31 16:27 UTC, merged