Implement merge method
breskul/bibernate pull request #16
Opened 2023-04-02 15:27 UTC by SeverinS

Added implementation of the `merge` method.

Depends on: #12 (add first level cache) PR

2023-04-04 17:43 UTC, yuriyfomin17 requested changes

2023-04-04 17:43 UTC, yuriyfomin17 commented on src/main/java/com/breskul/bibernate/persistence/EntityManagerImpl.java
> +    private <T> void mergeEntities(T newEntity, T oldEntity) {
The logic for merge `mergeEntities ` appears to be correct. However, we never send updates to database. Is this intentional ?

2023-04-04 17:55 UTC, yuriyfomin17 approved these changes

2023-04-06 16:34 UTC, ggazila approved these changes

2023-04-06 16:49 UTC, artemyankovets approved these changes

2023-04-06 19:53 UTC, yuriyfomin17 approved these changes

2023-04-06 19:54 UTC, merged